// Code generated by protoc-gen-go-netrpc. DO NOT EDIT.
// source: proto/empty.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// A generic empty message that you can re-use to avoid defining duplicated
// empty messages in your APIs. A typical example is to use it as the request
// or the response type of an API method. For instance:
//
//     service Foo {
//       rpc Bar(google.protobuf.Empty) returns (google.protobuf.Empty);
//     }
//
// The JSON representation for `Empty` is empty JSON object `{}`.
type Empty struct {
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc99f4026b6ec2c6, []int{0}
}

func init() {
	proto.RegisterType((*Empty)(nil), "proto.Empty")
}

func init() { proto.RegisterFile("proto/empty.proto", fileDescriptor_bc99f4026b6ec2c6) }

var fileDescriptor_bc99f4026b6ec2c6 = []byte{
	// 55 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0xcd, 0x2d, 0x28, 0xa9, 0xd4, 0x03, 0xb3, 0x85, 0x58, 0xc1, 0x94, 0x12, 0x3b,
	0x17, 0xab, 0x2b, 0x48, 0x34, 0x89, 0x0d, 0xcc, 0x37, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x1a,
	0xcb, 0xb1, 0xda, 0x2b, 0x00, 0x00, 0x00,
}
